apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: tk4ghqvsk-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-69e8f81962.t3km.p3.openshiftapps.com/rhtap/rhtap-qe:909eb8acb823aff406070bead545689cb7b2e540@sha256:73c5030523d9affaf69d3dad72e3ee166ab074dc32821e65c728c4cf724f3c39
        name: container-image  
